version: '3'

services:
  db:
    image: mysql:8.0.25
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_db
      MYSQL_PASSWORD: app123
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
