version: '2'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - ~/.docker-conf/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
