version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/.docker-conf/mongodb/data/db:/data/db
      - ~/.docker-conf/mongodb/data/configdb:/data/configdb
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME:root'
      - 'MONGO_INITDB_ROOT_PASSWORD:123'
    ports:
      - 27017:27017
